<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_littlefish_MuiCardMedia-root MuiCardMed_ad1681</name>
   <tag></tag>
   <elementGuidId>8f119f5d-c3f8-4af9-86db-45b9e4145e4e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.MuiCardMedia-root.MuiCardMedia-media.MuiCardMedia-img.css-1uahu4n</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f3d30736-3dd9-46a4-b2d5-6be678bba4cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiCardMedia-root MuiCardMedia-media MuiCardMedia-img css-1uahu4n</value>
      <webElementGuid>7e12b4f7-8ff0-436d-95d3-92c5d51e1179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/pages/login-background.png</value>
      <webElementGuid>6c4b8b2a-8d02-4458-8138-ead8a5e50f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>profile-header</value>
      <webElementGuid>61f0a2e5-e890-4f01-94cd-2f0457098643</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper css-uinsfl&quot;]/div[@class=&quot;layout-content-wrapper MuiBox-root css-34b9xr&quot;]/main[@class=&quot;layout-page-content css-zyg32b&quot;]/div[1]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation6 MuiCard-root css-12x00qv&quot;]/img[@class=&quot;MuiCardMedia-root MuiCardMedia-media MuiCardMedia-img css-1uahu4n&quot;]</value>
      <webElementGuid>8fff6d9e-caca-48e1-810a-eb4c5cd1f9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div/img</value>
      <webElementGuid>e725a922-f748-4104-a4ea-4c843c02cd9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='profile-header']</value>
      <webElementGuid>29437dfd-d2dc-4619-9f52-6842bf9e77a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>6b13c0f8-e89e-47e4-8369-ff9905b7d6d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/images/pages/login-background.png' and @alt = 'profile-header']</value>
      <webElementGuid>d31472a5-4f6e-4193-84b9-f9c2005ae77c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
