<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign InPlease sign-in to your account a_2f100a</name>
   <tag></tag>
   <elementGuidId>ae4bf13d-5158-481b-ad59-ee7cac177dcd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-d58qmv</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8f0446e8-93c8-4efa-83ed-68c9b3507e58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-d58qmv</value>
      <webElementGuid>766dbbbd-7706-47fb-94be-6e0bc9094162</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign InPlease sign-in to your account and start the adventureEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.</value>
      <webElementGuid>4781f675-b742-4f10-8c06-4787f46072c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;content-right MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-v9iy8c&quot;]/div[@class=&quot;MuiBox-root css-d58qmv&quot;]</value>
      <webElementGuid>07676f9b-b744-45d3-a826-b19e745d51bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div</value>
      <webElementGuid>c5e4844d-3928-45ec-8ab5-d2c9dd78d4f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>4523e2c7-fae2-4348-bdf6-4a0cfa8698ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign InPlease sign-in to your account and start the adventureEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.' or . = 'Sign InPlease sign-in to your account and start the adventureEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.')]</value>
      <webElementGuid>4b9994db-9234-4a7a-8550-b4e6bf788849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
