<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_auth-login-v2-password</name>
   <tag></tag>
   <elementGuidId>6f4d95b0-6e78-472b-bdec-e455b0c95af5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#auth-login-v2-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='auth-login-v2-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aea87167-de48-457f-968b-46cf38bfc5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e7da7ee8-53c7-42b0-9f2a-6e8f5973f364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auth-login-v2-password</value>
      <webElementGuid>d5b287d8-dd4a-423d-933a-23fb1bff0f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>6df7d51c-3336-4052-b965-b6f4a4439973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputAdornedEnd css-1jyh38l</value>
      <webElementGuid>9fe2c190-bfcf-40ea-a69c-d3e26f08c176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>!QAZxsw21</value>
      <webElementGuid>ae3bf67c-34ba-41c5-aa01-840546bf919e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auth-login-v2-password&quot;)</value>
      <webElementGuid>49731463-dc5f-4435-8be0-00bb7218c091</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='auth-login-v2-password']</value>
      <webElementGuid>a00a1f99-1827-4c02-ba6b-b4af97d76b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div/div/form/div[2]/div/input</value>
      <webElementGuid>79ae92bb-7d77-4eda-85a8-9ffb35efb87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>204d8c26-0e13-4128-b4a8-439bdd5ce1e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'auth-login-v2-password' and @type = 'password']</value>
      <webElementGuid>336d56fd-e3be-4597-8b4e-cd8e35151241</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
