<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign InEmailEmailPasswordPasswordForgot_5b93a2</name>
   <tag></tag>
   <elementGuidId>a65b44b4-5fcd-459c-890f-654511737609</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-d58qmv</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div/div/div[3]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>div:nth-child(3) > div</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9c6bab21-fc2b-4bfb-82d8-c50ffd9d7890</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-d58qmv</value>
      <webElementGuid>175c9532-3c8c-4352-a481-ff87ec410e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sign InEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.</value>
      <webElementGuid>2270330e-0c80-4e75-96d0-9061ed035b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper MuiBox-root css-33gw4&quot;]/div[@class=&quot;app-content MuiBox-root css-1bguz3s&quot;]/div[@class=&quot;content-right MuiBox-root css-0&quot;]/div[@class=&quot;MuiBox-root css-v9iy8c&quot;]/div[@class=&quot;MuiBox-root css-d58qmv&quot;]</value>
      <webElementGuid>6286c9fd-0e12-4da7-8621-16e388477228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div/div/div[3]/div</value>
      <webElementGuid>c4798f45-1241-4ba3-a88b-1bcad29f2058</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div</value>
      <webElementGuid>6826df6e-9f8f-4409-be40-745d9cd1b23e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Sign InEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.' or . = 'Sign InEmailEmailPasswordPasswordForgot Password?Sign InProtected by reCAPTCHA and subject to the Privacy Policy and Terms of Service.')]</value>
      <webElementGuid>abe2e41e-0c27-419c-9efe-1c75c07d950f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
