<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Low Stock Value_attribute-value-input-abc</name>
   <tag></tag>
   <elementGuidId>814d4d82-ff72-478b-b703-fd73d2774af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attribute-value-input-abc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#attribute-value-input-abc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a691efff-7ce8-4080-b9ef-9de6c6b1c798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b466f826-9349-47b0-8e1d-9de861f0ccfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attribute-value-input-abc</value>
      <webElementGuid>42557674-6ba7-44e3-a99b-dac981519151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter abc option</value>
      <webElementGuid>f076e630-9d2e-4433-8645-1fa690058925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df7d0125-f715-4f02-997c-32d679dd923e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1658vn9</value>
      <webElementGuid>010ccf0e-c2c6-40d7-b916-1f7ca2df8bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attribute-value-input-abc&quot;)</value>
      <webElementGuid>ecf2a3ea-6401-4ac0-9cba-fe5a4ec25ef9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attribute-value-input-abc']</value>
      <webElementGuid>8e96d112-1add-4a9b-9f63-e782172419f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[7]/div/form/div/div/div/div/input</value>
      <webElementGuid>1f97614b-dc82-4481-b7c8-2151ed6d7d6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/form/div/div/div/div/input</value>
      <webElementGuid>0faa6d3f-48c6-4b36-9e23-92748f235168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'attribute-value-input-abc' and @placeholder = 'Enter abc option' and @type = 'text']</value>
      <webElementGuid>db4b0f7f-bf73-4c11-8200-7126dfe6e6c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
