<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remove_isManagedVariantsStock</name>
   <tag></tag>
   <elementGuidId>3353b9f0-4417-48bf-a1ec-f4974fc96b9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#isManagedVariantsStock</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='isManagedVariantsStock']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Manage inventory for variants&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c05ae3f-c6c2-4d0e-a70d-43f85a7f54e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>PrivateSwitchBase-input MuiSwitch-input css-1m9pwf3</value>
      <webElementGuid>7287d32a-3903-4ed4-9966-7e9a52008bef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>isManagedVariantsStock</value>
      <webElementGuid>2f452a47-1c92-4f35-87a9-64c4a347ce28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>isManagedVariantsStock</value>
      <webElementGuid>09bd428b-dcd1-477b-b59d-44fc14e1bb52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>ff8a63f2-33f2-4a79-8991-2f3488e8f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;isManagedVariantsStock&quot;)</value>
      <webElementGuid>e9b29459-f62a-4822-9ec1-0f817d4d64d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='isManagedVariantsStock']</value>
      <webElementGuid>f7a9b218-b773-4f8c-a2d4-bdb586dafd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[8]/div/form/div[2]/label/span/span/input</value>
      <webElementGuid>a00cd41e-4812-41cc-8483-424e63bd6ca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/label/span/span/input</value>
      <webElementGuid>0f919581-8ffb-4b99-9d04-0e7721d4a927</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'isManagedVariantsStock' and @name = 'isManagedVariantsStock' and @type = 'checkbox']</value>
      <webElementGuid>3afb145a-c12d-424a-aca6-bdf4ce27d77a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
