<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Options_attribute-value-input_97991f</name>
   <tag></tag>
   <elementGuidId>b04ea5e9-8d9c-4798-b4be-02b4d1749d50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#attribute-value-input-Front-End</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='attribute-value-input-Front-End']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4aa64c8e-2dc7-4e95-a7ff-c0c5f0e23ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>dd81bacb-1df1-4799-b6b6-96b7b3cdb4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>attribute-value-input-Front-End</value>
      <webElementGuid>354aeb06-9854-4685-976c-ef10d7a3b835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Front-End option</value>
      <webElementGuid>3ab852d7-5a92-42b4-94b7-63b70d514c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9faffa29-f2f2-4f3e-a689-1fbad3cd4ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1658vn9</value>
      <webElementGuid>458c5a92-244b-4267-9146-ca2d520744b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;attribute-value-input-Front-End&quot;)</value>
      <webElementGuid>01d7c469-66b8-4a86-a78b-55bb8b7a2294</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='attribute-value-input-Front-End']</value>
      <webElementGuid>e1bb45c5-0c0d-485a-87da-f845da1b13d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[7]/div/form/div/div[2]/div/input</value>
      <webElementGuid>7e66eed6-7060-4407-a300-f51a377a674b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/input</value>
      <webElementGuid>7ea4105b-e27c-4c73-8f01-105af3b90ed2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'attribute-value-input-Front-End' and @placeholder = 'Enter Front-End option' and @type = 'text']</value>
      <webElementGuid>7d7828c1-8760-4fde-a8e4-0f473918b092</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
