<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Product Options_new-attribute-input</name>
   <tag></tag>
   <elementGuidId>b217804b-c81a-4fdd-8a94-09947a36491f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new-attribute-input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-attribute-input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a75b9266-1ad5-4db3-ba46-8665d0309edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>47d036a8-4862-436e-bf2b-add84d5e692e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-attribute-input</value>
      <webElementGuid>44ab4e20-17af-4648-8ef5-2e39f19c955c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter exact variant name to: add/remove</value>
      <webElementGuid>5719b911-67bc-46a8-99d5-f7e51da9ac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e447fed0-3b05-4d77-b335-6602b1c5506f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1658vn9</value>
      <webElementGuid>29d55bb0-5abf-4cf6-a936-094035726838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-attribute-input&quot;)</value>
      <webElementGuid>4acca5c2-2086-4a44-9a61-6fe2b74fbd3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-attribute-input']</value>
      <webElementGuid>d7c8d06e-2916-4432-a047-78f7ac9ca973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[7]/div/form/div[2]/div/div/input</value>
      <webElementGuid>f922f972-a0f3-4a26-a547-1ba0aded6db4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/form/div[2]/div/div/input</value>
      <webElementGuid>44c0978b-3ab9-4c65-9a17-79f335305779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'new-attribute-input' and @placeholder = 'Enter exact variant name to: add/remove' and @type = 'text']</value>
      <webElementGuid>bd31c4d2-bc6f-45ee-b7cc-c5a3086f039d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
