<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_SKU_new-attribute-input</name>
   <tag></tag>
   <elementGuidId>c9aa810e-99ee-4d1e-8757-77882c6238c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new-attribute-input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#new-attribute-input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2bfc1591-93c1-4809-84be-5fd392d13e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>11d97ea3-4dda-4dee-9377-b255df35d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new-attribute-input</value>
      <webElementGuid>74cb5484-aac2-4ab3-9d6a-909569a141eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter exact variant name to add/remove</value>
      <webElementGuid>876ae597-c447-41f5-9f3e-bd23c6e4ab36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f15eb5ff-57fe-4e56-9845-e7227a083b34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall css-1658vn9</value>
      <webElementGuid>00de3b12-1f62-49f2-8e1f-11ff8217ee5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new-attribute-input&quot;)</value>
      <webElementGuid>4ac0be35-c146-43f5-9a17-ccb259846150</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new-attribute-input']</value>
      <webElementGuid>00e6dfc9-7dd2-4b16-8a40-431be154ea4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div[7]/div/form/div[3]/div/div/input</value>
      <webElementGuid>66b4b84d-fc87-4257-b1af-98db75d08636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>e285fd52-c7c1-44a9-99e0-d61af2becdda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'new-attribute-input' and @placeholder = 'Enter exact variant name to add/remove' and @type = 'text']</value>
      <webElementGuid>abf12fca-9a7f-405e-b56d-cf39abde0de8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
