<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1 userStore Manager1 userSupervisor0 us_0874f6</name>
   <tag></tag>
   <elementGuidId>a538e082-8ab2-4f91-b3a6-bd3ef793babd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/div/div[2]/main/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.MuiBox-root.css-e9ziab</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a5a92e3f-e046-44d9-a862-255826132d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiBox-root css-e9ziab</value>
      <webElementGuid>eeeb9583-2043-4201-9392-b54f75f7c945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 userStore Manager1 userSupervisor0 usersCashier1 userAdministrator0 usersTest Role0 usersTest 2 Role0 usersTest Role 30 usersTest Role update0 usersTest Role updated0 usersStore Manager0 usersNew Descriptions0 usersNew Role0 usersNew Role0 users0 users0 users0 usersCreate New Role</value>
      <webElementGuid>23320e90-65f5-462f-a5e6-20a8148da466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/div[@class=&quot;layout-wrapper css-uinsfl&quot;]/div[@class=&quot;layout-content-wrapper MuiBox-root css-34b9xr&quot;]/main[@class=&quot;layout-page-content css-zyg32b&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-6 css-h2qpui&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 css-1jc81d0&quot;]/div[@class=&quot;MuiBox-root css-e9ziab&quot;]</value>
      <webElementGuid>6e31b17b-b994-41ba-a02c-5c123dad7547</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/main/div/div/div</value>
      <webElementGuid>10b48f0b-983b-443a-9230-d81b34516801</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Administrator'])[1]/following::div[50]</value>
      <webElementGuid>fa288e1d-4f3f-4b48-8b71-68e39c87cd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='littlefish'])[1]/following::div[57]</value>
      <webElementGuid>1ffa7297-56be-4a35-bfbc-a017d9c93630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div/div/div</value>
      <webElementGuid>fbc80667-59d0-41de-b131-a76aa938e0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1 userStore Manager1 userSupervisor0 usersCashier1 userAdministrator0 usersTest Role0 usersTest 2 Role0 usersTest Role 30 usersTest Role update0 usersTest Role updated0 usersStore Manager0 usersNew Descriptions0 usersNew Role0 usersNew Role0 users0 users0 users0 usersCreate New Role' or . = '1 userStore Manager1 userSupervisor0 usersCashier1 userAdministrator0 usersTest Role0 usersTest 2 Role0 usersTest Role 30 usersTest Role update0 usersTest Role updated0 usersStore Manager0 usersNew Descriptions0 usersNew Role0 usersNew Role0 users0 users0 users0 usersCreate New Role')]</value>
      <webElementGuid>2ebbdb5f-019d-4388-a6c1-4b6eafb7004b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
